services:
  - type: web
    name: shopify-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://react-frontend-9wcj.onrender.com
